#!/usr/bin/env python3
"""Emit sitemap.xml, robots.txt and llms.txt by reading the built pages.

Everything here is derived, never typed. The previous sitemap was hand-kept
and had already drifted once; a sitemap that lists a page which no longer
exists, or omits one that does, is worse than none, because Search Console
reports it as an error against the whole property.

Rules, all enforced by reading the page rather than by a list kept here:
  * a page with `noindex` in its robots meta is excluded from all three files
  * a page with no canonical is excluded (it is not a destination)
  * lastmod comes from git's last commit touching the file, so it is true

Run from the repo root, after the page scripts:  python3 scripts/build_meta.py
"""
import pathlib, re, subprocess, sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from pages import ROOT, SITE, MAIL

SKIP_DIRS = {"assets", "books", "_dev", "scripts", "scrollcraft", "node_modules",
             ".git", "api", ".vercel"}

# Priority and change frequency are hints, not facts, so they live here rather
# than being invented per page. Anything unlisted takes the default.
WEIGHT = {
    "/":               ("1.0", "monthly"),
    "/work":           ("0.9", "monthly"),
    "/services":       ("0.9", "monthly"),
    "/contact":        ("0.9", "yearly"),
    "/pricing":        ("0.8", "monthly"),
    "/web-design-jupiter-fl": ("0.8", "monthly"),
    "/insights":       ("0.7", "weekly"),
    "/studio":         ("0.7", "yearly"),
    "/process":        ("0.7", "yearly"),
}
DEFAULT = ("0.6", "yearly")


def html_files():
    for p in sorted(ROOT.rglob("*.html")):
        rel = p.relative_to(ROOT)
        if rel.parts[0] in SKIP_DIRS:
            continue
        yield p


def field(html, pattern):
    m = re.search(pattern, html, re.I)
    return m.group(1).strip() if m else ""


def lastmod(p):
    """The real date of the last commit touching this file."""
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", str(p.relative_to(ROOT))],
            cwd=ROOT, capture_output=True, text=True, timeout=10)
        return out.stdout.strip()
    except Exception:
        return ""


def collect():
    out = []
    for p in html_files():
        html = p.read_text()
        robots = field(html, r'<meta name="robots" content="([^"]*)"')
        canon = field(html, r'<link rel="canonical" href="([^"]*)"')
        if "noindex" in robots.lower() or not canon:
            continue
        out.append({
            "path": canon[len(SITE):] or "/",
            "url": canon,
            "title": re.sub(r"\s*&mdash;\s*", " — ",
                            field(html, r"<title>(.*?)</title>")).replace("&amp;", "&"),
            "desc": field(html, r'<meta name="description" content="([^"]*)"')
                      .replace("&amp;", "&").replace("&mdash;", "—"),
            "lastmod": lastmod(p),
            "file": p,
        })
    order = list(WEIGHT)
    out.sort(key=lambda e: (order.index(e["path"]) if e["path"] in order else 99, e["path"]))
    return out


def sitemap(entries):
    rows = []
    for e in entries:
        pri, freq = WEIGHT.get(e["path"], DEFAULT)
        lm = f"<lastmod>{e['lastmod']}</lastmod>" if e["lastmod"] else ""
        rows.append(f"  <url><loc>{e['url']}</loc>{lm}"
                    f"<changefreq>{freq}</changefreq><priority>{pri}</priority></url>")
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            "<!-- Generated by scripts/build_meta.py. Do not edit by hand: it is\n"
            "     rebuilt from the canonical tag of every page that is not noindex,\n"
            "     so it cannot list a page that does not exist or miss one that does.\n"
            "     /pay is absent because it is noindex — a client billing utility. -->\n"
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            + "\n".join(rows) + "\n</urlset>\n")


def robots():
    return f"""# {SITE}
User-agent: *
Allow: /

# The billing utility is noindex in its own head; this keeps a crawler from
# spending a request to find that out.
Disallow: /pay
Disallow: /api/

# Answer engines are welcome, and there is a digest written for them.
# See {SITE}/llms.txt

Sitemap: {SITE}/sitemap.xml
"""


def llms(entries):
    """A plain-text digest for answer engines.

    Search engines read the pages; assistants increasingly read a summary and
    cite from it. This gives them accurate, first-party facts to cite rather
    than leaving them to infer the business from marketing copy — and it is
    the one place where what we will *not* claim is stated outright.
    """
    lines = [
        "# Design of Man",
        "",
        "> A two-person web studio in Jupiter, Florida. We design, build and then keep",
        "> running websites and web apps for small businesses — mostly clinics, trades",
        "> and local service companies in Palm Beach and Martin County.",
        "",
        "## What we do",
        "",
        "- Custom website design and development, built from a written scope rather than a template.",
        "- Web and mobile app work: booking, accounts, payments, dashboards.",
        "- Ongoing care: managed hosting, security updates, backups, content changes, uptime alerts.",
        "- Technical SEO, Core Web Vitals and analytics.",
        "",
        "## How we work",
        "",
        "- Discover, design, build, launch, care. One point of contact throughout.",
        "- Price is fixed in writing before work starts and does not move unless the",
        "  scope does. Typical build: two to three weeks for a small site.",
        "- No published price list, because a five-page site for a trade and a booking",
        "  platform with accounts are not the same job. A free 30-minute consult ends",
        "  with a written scope and one number, yours to keep either way.",
        "",
        "## Verifiable results",
        "",
        "- First Rehabilitation of North Palm Beach (launched 20 July 2026): +50% organic",
        "  clicks and +132% search impressions in the 32 days after launch versus the 32",
        "  before, weekday-to-weekday, per Google Search Console. 22 enquiries through the",
        "  site's own form in the first 30 days; the previous site had no lead capture.",
        "",
        "## What we do not claim",
        "",
        "- No load-time improvement is claimed for that project: no performance baseline",
        "  was captured for the previous site, so there is nothing to compare against.",
        "- We publish no testimonials we cannot attribute, and no client metric we did not",
        "  measure. If a figure is not on this list, we have not stood behind it.",
        "",
        "## Contact",
        "",
        f"- Email: {MAIL}",
        "- Location: Jupiter, Florida, United States. Serving Palm Beach County, Martin",
        "  County, and remote clients across the US.",
        "- Hours: Monday to Friday, 9am to 5pm Eastern. Email answered within one business day.",
        "- There is no published telephone number.",
        "",
        "## Pages",
        "",
    ]
    for e in entries:
        lines.append(f"- [{e['title']}]({e['url']}): {e['desc']}")
    lines.append("")
    return "\n".join(lines)


def main():
    entries = collect()
    for name, body in (("sitemap.xml", sitemap(entries)),
                       ("robots.txt", robots()),
                       ("llms.txt", llms(entries))):
        (ROOT / name).write_text(body)
        print(f"  {name:26} {len(body):7,} bytes")
    print(f"  {len(entries)} indexable pages")


if __name__ == "__main__":
    main()
